version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: crusher-postgres
    restart: always
    environment:
      POSTGRES_DB: crusher_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Uncomment below if you want to run the app in Docker too
  # app:
  #   build: .
  #   container_name: crusher-backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@postgres:5432/crusher_backend
  #     NODE_ENV: development
  #     PORT: 3000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  postgres_data:
